### ISSUE TITLE
Edge case using VAT

### ISSUE THREAD

**Issue by robert-stanciu** [josemmo/einvoicing#48]
Hello,

I have the following scenario that's not outputting the correct total.
I know it's not a bug, but what would be a valid solution?

This is the code that's creating an invoice line with a 100k quantity and the price of 100 including VAT (that's why 100 / 1.19)

```php
$line = (new \Einvoicing\InvoiceLine())
            ->setQuantity(100_000)
            ->setPrice(100 / 1.19)
            ->setVatRate(19);
$invoice = (new \Einvoicing\Invoice(CiusRo::class))
    ->addLine($line);
echo $invoice->getTotals()->taxInclusiveAmount;
``` 
The output of this code is 9.999.999,99 instead of 10.000.000

**Comment by floriankraemer** [comment]
This is very likely an issue with the internals of PHP float calculation somewhere. That's why in PHP and also JS and similar languages specialized libraries are used to avoid exactly this problem.

If you can figure out the place where the calculation is done (I just stumbled 2 minutes ago across this library), then you can try to use something like https://github.com/piggly-dev/php-decimal to fix the issue. I recommend to start with a unit test for this case to prove the problem and then fix it.

**Comment by robert-stanciu** [comment]
Today I found that this behavior happens in the UBL reader too.
Because of the roundings that might appear, the invoice line price won't have enough precision to calculate the invoice totals.

This is a solution: https://github.com/robert-stanciu/einvoicing/pull/3

P.S.: I am aware that this edge case can appear only in certain countries.

**Comment by josemmo** [comment]
Hello @robert-stanciu,

Sorry for the delay.

This is because EN 16931 mandates the price without VAT of an item has to be rounded to 2 decimals. AFAIK, this is just how the specification works.

Maybe CIUS-RO has different decimal precision for some of the invoice fields, but I cannot find the specification in English to verify it.
